name: rl-demo 
channels:
  - defaults 
  - conda-forge 
dependencies:
  - python=3.13
  - pip=25.2
  - numpy=2.3.1
  - pybullet=3.25
  - gymnasium=0.28.1
  - stable-baselines3=2.3.2
  - pip:
    - onshape-to-robot
    - stable_baselines3[extra]